{{- if .Values.installCRDs }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-pre-manifests
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
data:
  crds-configmaps.yaml: |-
      {{ range $path, $bytes := .Files.Glob (printf "_crds/*")}}
      {{- $.Files.Get $path | nindent 8 }}
      {{ end }}
{{- end -}}
