{{- if .Values.installCRDs }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-pre-hook-install-crds
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "2"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      name: {{ .Release.Name }}
      labels:
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
    spec:
      serviceAccountName: {{ .Release.Name }}-pre-hook-job
      restartPolicy: Never
      containers:
      - name: install-crds
        image: {{ include "cloudtty.cloudshell.image" . }}
        imagePullPolicy: IfNotPresent
        workingDir: /crds
        command:
        - /bin/sh
        - -c
        - |
          bash <<'EOF'
          set -ex
          kubectl apply --server-side -f /crds --force-conflicts
          EOF
        volumeMounts:
        - name: crds
          mountPath: /crds
      volumes:
      - name: crds
        configMap:
          name: {{ .Release.Name }}-pre-manifests
{{- end -}}
