{{- if .Values.installCRDs }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-pre-hook-job
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-5"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
{{- end -}}